[project]
name = 'JSwap'
description = 'A smart contract that converts btc to stacks'
authors = [Gbolahan Akande]
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.JSwap]
path = 'contracts/JSwap.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
